# Post-S2 Workflow Configuration for Hugin
# Configuration for workflow after S2 (species detection) is complete

# Database configuration
database:
  path: "data/hugin_post_s2.db"  # SQLite database for post-S2 data
  # Note: Database files are excluded from Git via .gitignore

# Image analysis configuration
image_analysis:
  species_detection: true          # Enable species detection
  confidence_threshold: 0.5        # Minimum confidence for species detection
  batch_size: 100                  # Process images in batches
  include_metadata: true           # Include image metadata
  export_detections: true          # Export detection results

# Location clustering configuration
location_clustering:
  enabled: true                    # Enable location clustering
  radius_meters: 5.0              # Cluster radius (5m = 10m diameter)
  min_points: 1                   # Minimum points to form a cluster
  auto_cluster: true              # Automatically cluster locations
  max_cluster_distance: 10.0      # Maximum distance for point assignment
  include_boundaries: true         # Calculate cluster boundaries

# Data condensation configuration
data_condensation:
  enabled: true                    # Enable data condensation
  time_window_minutes: 10          # Time window for condensation (10 minutes)
  aggregation_method: "count"      # Aggregation method (count, sum, mean)
  include_species_breakdown: true  # Include species breakdown in condensation
  export_condensed: true           # Export condensed data
  include_temporal_patterns: true  # Include temporal pattern analysis

# Output configuration
output:
  include_cluster_names: true      # Include cluster names in output
  unknown_cluster_prefix: "Unknown_Cluster_"  # Prefix for unknown clusters
  export_formats: ["json", "csv", "geojson", "kml"]  # Export formats
  decouple_labeling: true          # Decouple labeling from processing
  include_statistics: true         # Include cluster statistics
  include_boundaries: true         # Include cluster boundaries
  include_analytics: true          # Include analytics data

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/post_s2_workflow.log"

# Processing settings
processing:
  batch_size: 1000                # Process observations in batches
  parallel_workers: 4              # Number of parallel workers
  memory_limit_mb: 1024           # Memory limit for processing
  gps_accuracy_threshold: 10.0     # Minimum GPS accuracy required (meters)

# Workflow automation
workflow:
  auto_cluster_after_s2: true      # Automatically cluster after S2
  auto_condense_data: true         # Automatically condense data
  auto_export_results: true        # Automatically export results
  require_manual_approval: false   # Require manual approval for clustering

# Quality control
quality:
  min_accuracy_meters: 5.0         # Minimum GPS accuracy required
  max_age_days: 365               # Maximum age of observations to process
  outlier_threshold: 50.0         # Distance threshold for outlier detection
  validate_coordinates: true      # Validate GPS coordinates
  validate_species: true           # Validate species detection results

# Integration settings
integration:
  s2_results_format: "json"        # Expected S2 results format
  output_integration: true         # Integrate with other Hugin outputs
  analytics_integration: true      # Integrate with Hugin analytics
  export_integration: true         # Integrate with Hugin export system
