services:
  localstack:
    image: localstack/localstack:latest
    container_name: wildlife-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,lambda,logs,iam,cloudwatch,stepfunctions,batch,ecs,ecr,events
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./infra:/opt/code/infra"
    networks:
      - wildlife-network

  # Optional: Add a simple web interface for LocalStack
  localstack-ui:
    image: localstack/localstack-pro:latest
    container_name: wildlife-localstack-ui
    ports:
      - "8080:8080"
    environment:
      - LOCALSTACK_HOST=localstack
    depends_on:
      - localstack
    networks:
      - wildlife-network

networks:
  wildlife-network:
    driver: bridge

