version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "file": "%(filename)s", "line": %(lineno)d, "function": "%(funcName)s", "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  app_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/app/application.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug/debug.log
    maxBytes: 52428800  # 50MB
    backupCount: 3
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8
  
  audit_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/audit/audit.log
    maxBytes: 10485760  # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  # Application loggers
  odin:
    level: INFO
    handlers: [console, app_file, debug_file, error_file]
    propagate: false
  
  munin:
    level: INFO
    handlers: [console, app_file, debug_file, error_file]
    propagate: false
  
  hugin:
    level: INFO
    handlers: [console, app_file, debug_file, error_file]
    propagate: false
  
  # Infrastructure loggers
  infrastructure:
    level: INFO
    handlers: [console, app_file, debug_file, error_file, audit_file]
    propagate: false
  
  # Security and audit loggers
  security:
    level: INFO
    handlers: [console, error_file, audit_file]
    propagate: false
  
  audit:
    level: INFO
    handlers: [audit_file]
    propagate: false
  
  # Third-party library loggers
  boto3:
    level: WARNING
    handlers: [console, app_file]
    propagate: false
  
  botocore:
    level: WARNING
    handlers: [console, app_file]
    propagate: false
  
  urllib3:
    level: WARNING
    handlers: [console, app_file]
    propagate: false
  
  requests:
    level: WARNING
    handlers: [console, app_file]
    propagate: false

root:
  level: INFO
  handlers: [console, app_file, debug_file, error_file]

